/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT = 1,
  anon_sym_technique = 2,
  aux_sym_magic_line_token1 = 3,
  anon_sym_v = 4,
  sym_version = 5,
  anon_sym_BANG = 6,
  anon_sym_SEMI = 7,
  anon_sym_LPARENc_RPAREN = 8,
  anon_sym_LPARENC_RPAREN = 9,
  anon_sym_u00a9 = 10,
  sym_license = 11,
  aux_sym_copyright_token1 = 12,
  anon_sym_AMP = 13,
  anon_sym_COLON = 14,
  anon_sym_DASH_GT = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_COMMA = 20,
  sym_forma = 21,
  sym_identifier = 22,
  sym_newline = 23,
  sym_source_file = 24,
  sym_header_block = 25,
  sym_magic_line = 26,
  sym_spdx_line = 27,
  sym_copyright = 28,
  sym_template_line = 29,
  sym_template = 30,
  sym_procedure_declaration = 31,
  sym_genus = 32,
  sym_unit_genus = 33,
  sym_simple_genus = 34,
  sym_list_genus = 35,
  sym_tuple_genus = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_source_file_repeat2 = 38,
  aux_sym_tuple_genus_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT] = "%",
  [anon_sym_technique] = "technique",
  [aux_sym_magic_line_token1] = "magic_line_token1",
  [anon_sym_v] = "v",
  [sym_version] = "version",
  [anon_sym_BANG] = "!",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPARENc_RPAREN] = "(c)",
  [anon_sym_LPARENC_RPAREN] = "(C)",
  [anon_sym_u00a9] = "\u00a9",
  [sym_license] = "license",
  [aux_sym_copyright_token1] = "copyright_token1",
  [anon_sym_AMP] = "&",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [sym_forma] = "forma",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym_header_block] = "header_block",
  [sym_magic_line] = "magic_line",
  [sym_spdx_line] = "spdx_line",
  [sym_copyright] = "copyright",
  [sym_template_line] = "template_line",
  [sym_template] = "template",
  [sym_procedure_declaration] = "procedure_declaration",
  [sym_genus] = "genus",
  [sym_unit_genus] = "unit_genus",
  [sym_simple_genus] = "simple_genus",
  [sym_list_genus] = "list_genus",
  [sym_tuple_genus] = "tuple_genus",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_tuple_genus_repeat1] = "tuple_genus_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_technique] = anon_sym_technique,
  [aux_sym_magic_line_token1] = aux_sym_magic_line_token1,
  [anon_sym_v] = anon_sym_v,
  [sym_version] = sym_version,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPARENc_RPAREN] = anon_sym_LPARENc_RPAREN,
  [anon_sym_LPARENC_RPAREN] = anon_sym_LPARENC_RPAREN,
  [anon_sym_u00a9] = anon_sym_u00a9,
  [sym_license] = sym_license,
  [aux_sym_copyright_token1] = aux_sym_copyright_token1,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_forma] = sym_forma,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym_header_block] = sym_header_block,
  [sym_magic_line] = sym_magic_line,
  [sym_spdx_line] = sym_spdx_line,
  [sym_copyright] = sym_copyright,
  [sym_template_line] = sym_template_line,
  [sym_template] = sym_template,
  [sym_procedure_declaration] = sym_procedure_declaration,
  [sym_genus] = sym_genus,
  [sym_unit_genus] = sym_unit_genus,
  [sym_simple_genus] = sym_simple_genus,
  [sym_list_genus] = sym_list_genus,
  [sym_tuple_genus] = sym_tuple_genus,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_tuple_genus_repeat1] = aux_sym_tuple_genus_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_technique] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_magic_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPARENc_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPARENC_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a9] = {
    .visible = true,
    .named = false,
  },
  [sym_license] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_copyright_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_forma] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header_block] = {
    .visible = true,
    .named = true,
  },
  [sym_magic_line] = {
    .visible = true,
    .named = true,
  },
  [sym_spdx_line] = {
    .visible = true,
    .named = true,
  },
  [sym_copyright] = {
    .visible = true,
    .named = true,
  },
  [sym_template_line] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_genus] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_genus] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_genus] = {
    .visible = true,
    .named = true,
  },
  [sym_list_genus] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_genus] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_genus_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_copyright = 1,
  field_license = 2,
  field_name = 3,
  field_parameters = 4,
  field_return_type = 5,
  field_template = 6,
  field_version = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_copyright] = "copyright",
  [field_license] = "license",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_template] = "template",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 3},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_license, 1},
  [2] =
    {field_template, 1},
  [3] =
    {field_name, 0},
    {field_parameters, 2},
    {field_return_type, 4},
  [6] =
    {field_version, 4},
  [7] =
    {field_copyright, 4},
    {field_license, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 44,
        '!', 24,
        '%', 19,
        '&', 33,
        '(', 37,
        ')', 38,
        ',', 41,
        '-', 4,
        ':', 34,
        ';', 25,
        '[', 39,
        ']', 40,
        't', 7,
        'v', 22,
        0xa9, 28,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == 'C') ADVANCE(3);
      if (lookahead == 'c') ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'q') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 14:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(30);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '!') ADVANCE(24);
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '&') ADVANCE(33);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == 0xa9) ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '(') ADVANCE(36);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(17);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_technique);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_magic_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPARENc_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPARENC_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_u00a9);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_license);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_license);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_copyright_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_copyright_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == 'c') ADVANCE(2);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_forma);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_technique] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPARENc_RPAREN] = ACTIONS(1),
    [anon_sym_u00a9] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_forma] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym_header_block] = STATE(6),
    [sym_magic_line] = STATE(4),
    [sym_procedure_declaration] = STATE(33),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_source_file_repeat2] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_forma,
    STATE(50), 1,
      sym_genus,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(20), 4,
      sym_unit_genus,
      sym_simple_genus,
      sym_list_genus,
      sym_tuple_genus,
  [23] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_forma,
    STATE(38), 1,
      sym_genus,
    STATE(20), 4,
      sym_unit_genus,
      sym_simple_genus,
      sym_list_genus,
      sym_tuple_genus,
  [42] = 5,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(23), 1,
      anon_sym_AMP,
    STATE(8), 1,
      sym_spdx_line,
    STATE(26), 1,
      sym_template_line,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      sym_identifier,
      sym_newline,
  [60] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_newline,
    STATE(10), 1,
      aux_sym_source_file_repeat2,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(32), 1,
      sym_procedure_declaration,
  [79] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_newline,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(10), 1,
      aux_sym_source_file_repeat2,
    STATE(32), 1,
      sym_procedure_declaration,
  [98] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_newline,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_source_file_repeat2,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(36), 1,
      sym_procedure_declaration,
  [117] = 3,
    ACTIONS(23), 1,
      anon_sym_AMP,
    STATE(21), 1,
      sym_template_line,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      sym_identifier,
      sym_newline,
  [129] = 1,
    ACTIONS(35), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_AMP,
      sym_identifier,
      sym_newline,
  [137] = 4,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_source_file_repeat2,
    STATE(36), 1,
      sym_procedure_declaration,
  [150] = 4,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_source_file_repeat2,
    STATE(32), 1,
      sym_procedure_declaration,
  [163] = 4,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_source_file_repeat2,
    STATE(37), 1,
      sym_procedure_declaration,
  [176] = 3,
    ACTIONS(41), 1,
      sym_newline,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [187] = 4,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(14), 1,
      aux_sym_source_file_repeat2,
    STATE(46), 1,
      sym_procedure_declaration,
  [200] = 1,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      anon_sym_AMP,
      sym_identifier,
      sym_newline,
  [207] = 3,
    ACTIONS(50), 1,
      sym_newline,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [218] = 3,
    ACTIONS(27), 1,
      sym_newline,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [229] = 1,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_AMP,
      sym_identifier,
      sym_newline,
  [236] = 1,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      sym_newline,
  [242] = 1,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      sym_newline,
  [248] = 1,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      sym_identifier,
      sym_newline,
  [254] = 1,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      sym_newline,
  [260] = 1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      sym_newline,
  [266] = 3,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym_tuple_genus_repeat1,
  [276] = 1,
    ACTIONS(71), 3,
      anon_sym_LPARENc_RPAREN,
      anon_sym_LPARENC_RPAREN,
      anon_sym_u00a9,
  [282] = 1,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      sym_identifier,
      sym_newline,
  [288] = 1,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      sym_identifier,
      sym_newline,
  [294] = 1,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      sym_newline,
  [300] = 3,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      aux_sym_tuple_genus_repeat1,
  [310] = 1,
    ACTIONS(79), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      sym_newline,
  [316] = 3,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym_tuple_genus_repeat1,
  [326] = 2,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      sym_newline,
  [333] = 2,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      sym_newline,
  [340] = 2,
    ACTIONS(88), 1,
      anon_sym_SEMI,
    ACTIONS(90), 1,
      sym_newline,
  [347] = 2,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(94), 1,
      sym_forma,
  [354] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      sym_newline,
  [361] = 2,
    ACTIONS(86), 1,
      sym_newline,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
  [368] = 1,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      sym_newline,
  [373] = 2,
    ACTIONS(100), 1,
      aux_sym_copyright_token1,
    STATE(57), 1,
      sym_copyright,
  [380] = 2,
    ACTIONS(102), 1,
      aux_sym_copyright_token1,
    STATE(55), 1,
      sym_template,
  [387] = 1,
    ACTIONS(81), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [392] = 1,
    ACTIONS(104), 1,
      sym_version,
  [396] = 1,
    ACTIONS(106), 1,
      anon_sym_v,
  [400] = 1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [404] = 1,
    ACTIONS(110), 1,
      sym_newline,
  [408] = 1,
    ACTIONS(86), 1,
      sym_newline,
  [412] = 1,
    ACTIONS(112), 1,
      sym_forma,
  [416] = 1,
    ACTIONS(114), 1,
      anon_sym_COLON,
  [420] = 1,
    ACTIONS(116), 1,
      anon_sym_technique,
  [424] = 1,
    ACTIONS(118), 1,
      anon_sym_DASH_GT,
  [428] = 1,
    ACTIONS(120), 1,
      sym_forma,
  [432] = 1,
    ACTIONS(122), 1,
      anon_sym_RBRACK,
  [436] = 1,
    ACTIONS(124), 1,
      sym_license,
  [440] = 1,
    ACTIONS(126), 1,
      sym_newline,
  [444] = 1,
    ACTIONS(128), 1,
      sym_newline,
  [448] = 1,
    ACTIONS(130), 1,
      sym_newline,
  [452] = 1,
    ACTIONS(132), 1,
      sym_newline,
  [456] = 1,
    ACTIONS(134), 1,
      aux_sym_magic_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 79,
  [SMALL_STATE(7)] = 98,
  [SMALL_STATE(8)] = 117,
  [SMALL_STATE(9)] = 129,
  [SMALL_STATE(10)] = 137,
  [SMALL_STATE(11)] = 150,
  [SMALL_STATE(12)] = 163,
  [SMALL_STATE(13)] = 176,
  [SMALL_STATE(14)] = 187,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 207,
  [SMALL_STATE(17)] = 218,
  [SMALL_STATE(18)] = 229,
  [SMALL_STATE(19)] = 236,
  [SMALL_STATE(20)] = 242,
  [SMALL_STATE(21)] = 248,
  [SMALL_STATE(22)] = 254,
  [SMALL_STATE(23)] = 260,
  [SMALL_STATE(24)] = 266,
  [SMALL_STATE(25)] = 276,
  [SMALL_STATE(26)] = 282,
  [SMALL_STATE(27)] = 288,
  [SMALL_STATE(28)] = 294,
  [SMALL_STATE(29)] = 300,
  [SMALL_STATE(30)] = 310,
  [SMALL_STATE(31)] = 316,
  [SMALL_STATE(32)] = 326,
  [SMALL_STATE(33)] = 333,
  [SMALL_STATE(34)] = 340,
  [SMALL_STATE(35)] = 347,
  [SMALL_STATE(36)] = 354,
  [SMALL_STATE(37)] = 361,
  [SMALL_STATE(38)] = 368,
  [SMALL_STATE(39)] = 373,
  [SMALL_STATE(40)] = 380,
  [SMALL_STATE(41)] = 387,
  [SMALL_STATE(42)] = 392,
  [SMALL_STATE(43)] = 396,
  [SMALL_STATE(44)] = 400,
  [SMALL_STATE(45)] = 404,
  [SMALL_STATE(46)] = 408,
  [SMALL_STATE(47)] = 412,
  [SMALL_STATE(48)] = 416,
  [SMALL_STATE(49)] = 420,
  [SMALL_STATE(50)] = 424,
  [SMALL_STATE(51)] = 428,
  [SMALL_STATE(52)] = 432,
  [SMALL_STATE(53)] = 436,
  [SMALL_STATE(54)] = 440,
  [SMALL_STATE(55)] = 444,
  [SMALL_STATE(56)] = 448,
  [SMALL_STATE(57)] = 452,
  [SMALL_STATE(58)] = 456,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_declaration, 2, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_block, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_block, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_magic_line, 6, 0, 5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(48),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spdx_line, 3, 0, 2),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spdx_line, 6, 0, 6),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_genus, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_genus, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_block, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_genus, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_genus, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_genus, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_genus, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_genus_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_genus_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_declaration, 5, 0, 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [108] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copyright, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_technique(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "technique",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
