name: Check
on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Clone project
              uses: actions/checkout@v3

            - name: Validate toolchain
              run: |
                  echo "RUST_VERSION=$(rustc --version | cut -d ' ' -f 2)" >> ${GITHUB_ENV}

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/debug
                  key: cargo-${{ runner.os }}-${{ runner.arch}}-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      cargo-${{ runner.os }}-${{ runner.arch}}-${{ env.RUST_VERSION }}-

            - name: Build sources
              run: |
                  cargo build

            - name: Run tests
              run: |
                  cargo test
